// ===================== MOEMZADE.GE =====================
const SHEET_ID='1weL4w0BzXGrYPIczj0kKYFdvE615OIMKSzIpt9Q1Yu0';
const SHEET_NAME='teachers';
const PAGE_SIZE=35;
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbxVMDPiywAB_J7dT5foF_Fja1K4blC_XHRHK9pWuGnZU0neLVp2h3D8lGBXXX9GR4JRJw/exec';
const ROUTES={home:'./',teachers:'teachers.html',teacher:'teacher.html',register:'register.html'};

const CATEGORY_DATA={
  'მუსიკა':['გიტარა','ფორტეპიანო / კლავიში','ვოკალი','სკრიპკა','დრამი','ბასი','უკულელე','DJ','მუსიკის თეორია','ხალხური ინსტრუმენტები','სხვა'],
  'ცეკვა':['ქართული ცეკვა','ბალეტი','ჰიპ-ჰოპი','ლათინო','სალსა','ბაჩატა','თანამედროვე ცეკვა','საბავშვო ცეკვა','წყვილური ცეკვა','სხვა'],
  'სილამაზე':['მაკიაჟი','ნეილ არტი','მანიკური','პედიკური','წარბები','წამწამები','თმის შეჭრა','თმის შეღებვა','კოსმეტოლოგია','მასაჟი','სხვა'],
  'სასკოლო საგნები':['მათემატიკა','ქართული ენა და ლიტერატურა','ინგლისური','რუსული','გერმანული','ფრანგული','ფიზიკა','ქიმია','ბიოლოგია','ისტორია','გეოგრაფია','სამოქალაქო განათლება','დაწყებითი კლასები','აბიტურიენტები','ეროვნული გამოცდები','სხვა'],
  'ტექნოლოგია':['პროგრამირება','ვებ-დეველოპმენტი','Python','JavaScript','HTML/CSS','React','WordPress','Excel','Google Sheets','Photoshop','Illustrator','Canva','UI/UX დიზაინი','კომპიუტერის საბაზისო სწავლება','სხვა'],
  'შემოქმედება':['ხატვა','ფერწერა','ფოტოგრაფია','ვიდეოგრაფია','მონტაჟი','მსახიობობა','ხელნაკეთი ნივთები','კერამიკა','დიზაინი','სხვა'],
  'ენები':['ინგლისური','რუსული','გერმანული','ფრანგული','იტალიური','ესპანური','თურქული','ჩინური','ქართული უცხოელებისთვის','სხვა'],
  'ხელსაქმე':['კერვა','ქარგვა','ქსოვა','ხელნაკეთი ნივთები','ავეჯის რესტავრაცია','ელექტროობა','სანტექნიკა','სხვა'],
  'სპორტი და ჯანმრთელობა':['ფიტნესი','იოგა','პილატესი','კრივი','ფეხბურთი','კალათბურთი','ცურვა','ჭადრაკი','რეაბილიტაცია','პერსონალური ტრენერი','სხვა'],
  'კულინარია':['კულინარია','საკონდიტრო','ტორტები','ქართული სამზარეულო','უცხოური სამზარეულო','ყავის მომზადება','სხვა'],
  'თეატრი და მედია':['მსახიობობა','სცენური მეტყველება','ტელე/რადიო წამყვანი','ვიდეო ბლოგინგი','სხვა'],
  'მართვა':['ავტომობილის მართვა','თეორია','პრაქტიკა','მოტო','სხვა'],
  'ბიზნესი და ფინანსები':['ბუღალტერია','მარკეტინგი','გაყიდვები','SMM','ბიზნესის დაწყება','ფინანსური განათლება','სხვა'],
  'სხვა':['სხვა']
};
const ICONS={'მუსიკა':'🎵','ცეკვა':'💃','სილამაზე':'💅','სასკოლო საგნები':'🎓','ტექნოლოგია':'💻','შემოქმედება':'🎨','ენები':'🌍','ხელსაქმე':'🔧','სპორტი და ჯანმრთელობა':'🏋️','კულინარია':'🍳','თეატრი და მედია':'🎭','მართვა':'🚗','ბიზნესი და ფინანსები':'💼','სხვა':'📦'};
const CATEGORIES=['',...Object.keys(CATEGORY_DATA).map(c=>`${ICONS[c]} ${c}`)];
const CAT_LABELS=['ყველა სფერო',...Object.keys(CATEGORY_DATA)];
const REGIONS=['','თბილისი','კახეთი','შიდა ქართლი','ქვემო ქართლი','მცხეთა-მთიანეთი','სამცხე-ჯავახეთი','იმერეთი','რაჭა-ლეჩხუმი და ქვემო სვანეთი','გურია','სამეგრელო-ზემო სვანეთი','აჭარა','აფხაზეთი'];
const REGION_SETTLEMENTS={
  'თბილისი':['თბილისი'],
  'კახეთი':['თელავი','გურჯაანი','ყვარელი','სიღნაღი','ლაგოდეხი','ახმეტა','დედოფლისწყარო','საგარეჯო','წნორი','სხვა'],
  'შიდა ქართლი':['გორი','ხაშური','ქარელი','კასპი','სურამი','აგარა','რუისი','ბრეთი','ქვიშხეთი','სხვა'],
  'ქვემო ქართლი':['რუსთავი','მარნეული','ბოლნისი','გარდაბანი','დმანისი','თეთრიწყარო','წალკა','კაზრეთი','სხვა'],
  'მცხეთა-მთიანეთი':['მცხეთა','დუშეთი','თიანეთი','სტეფანწმინდა','ჟინვალი','ფასანაური','სხვა'],
  'სამცხე-ჯავახეთი':['ახალციხე','ბორჯომი','ახალქალაქი','ნინოწმინდა','ადიგენი','ასპინძა','ბაკურიანი','სხვა'],
  'იმერეთი':['ქუთაისი','ზესტაფონი','სამტრედია','წყალტუბო','ჭიათურა','საჩხერე','ხონი','ვანი','ბაღდათი','თერჯოლა','ტყიბული','სხვა'],
  'რაჭა-ლეჩხუმი და ქვემო სვანეთი':['ამბროლაური','ონი','ცაგერი','ლენტეხი','სხვა'],
  'გურია':['ოზურგეთი','ლანჩხუთი','ჩოხატაური','ურეკი','სხვა'],
  'სამეგრელო-ზემო სვანეთი':['ზუგდიდი','ფოთი','სენაკი','მარტვილი','აბაშა','ხობი','წალენჯიხა','ჩხოროწყუ','მესტია','სხვა'],
  'აჭარა':['ბათუმი','ქობულეთი','ხელვაჩაური','ქედა','შუახევი','ხულო','სარფი','გონიო','მახინჯაური','სხვა'],
  'აფხაზეთი':['სოხუმი','გაგრა','გუდაუთა','ოჩამჩირე','გალი','ტყვარჩელი','სხვა']
};
const FORMATS=['','პირადად','ონლაინ','ორივე'];
const FMT_LABELS=['ნებისმიერი','პირადად','ონლაინ','ორივე'];
const PRICE_TYPES=['საათში','თვეში','კურსი','შეთანხმებით'];
const BG_COLORS=['bg-teal','bg-amber','bg-pink','bg-blue','bg-purple','bg-green'];
const AV_COLORS=['av-teal','av-amber','av-pink','av-blue','av-purple','av-green'];
let allTeachers=[],selectedCat='',selectedReg='',selectedSettlement='',selectedFmt='',selectedMinP=0,selectedMaxP=9999,searchQuery='',currentPage=1,activeFilter='',tempVal='';

function esc(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function stripEmoji(s){return String(s||'').replace(/^[^\wა-ჰ]+/,'').trim()}
function getInitials(n){return String(n||'').split(' ').map(w=>w[0]).join('').substring(0,2).toUpperCase()}
function colorIndex(n){let h=0;for(const c of String(n||''))h=(h*31+c.charCodeAt(0))&0xffffffff;return Math.abs(h)%6}
function toggleMenu(){document.getElementById('mobileMenu')?.classList.toggle('open')}
function fmtPrice(p,t){if(!p||t==='შეთანხმებით')return'შეთ.';return `${p}₾/${({'საათში':'სთ','თვეში':'თვე','კურსი':'კურსი'}[t]||'სთ')}`}
function place(t){return t.settlement||t.region||'—'}

function addRuntimeCss(){
  const css=`.tc-meta-row{display:flex;align-items:center;justify-content:space-between;gap:6px;margin:0 0 9px}.tc-place{font-size:10.5px;color:#666;background:#f5f5f1;border-radius:999px;padding:3px 7px;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tc-format{font-size:10px;color:#0F6E56;background:#E8F8F3;border-radius:999px;padding:3px 7px;font-weight:800;white-space:nowrap}.tc-open{font-size:10.5px;color:#aaa;background:#fafaf8;border-radius:999px;padding:4px 8px;white-space:nowrap}.tc-region{display:none!important}.tc-online-badge{position:absolute;top:8px;right:8px;background:rgba(255,255,255,.94);color:#0F6E56;border-radius:999px;padding:4px 9px;font-size:10px;font-weight:800;box-shadow:0 5px 14px rgba(0,0,0,.12)}.contact-btn-main.whatsapp{background:#1DA851}.filter-pills{scrollbar-width:none}.filter-pills::-webkit-scrollbar{display:none}@media(max-width:768px){.filter-pills{width:100%;overflow-x:auto;flex-wrap:nowrap;padding-bottom:3px}.filter-pill{flex:0 0 auto}.teachers-grid,.featured-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important}.tc-body{padding:9px 9px 10px}.tc-name{font-size:12.5px;line-height:1.25}.tc-sub{font-size:10.8px;line-height:1.25;min-height:14px}.tc-price{font-size:12px}.tc-place,.tc-format{font-size:9.5px;padding:3px 6px}.page-hero{top:56px}.ph-right{width:100%;margin-left:0}.cat-card{padding:13px 7px}.cat-name{font-size:10.5px}}`;
  const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
}
function cleanLinks(){document.querySelectorAll('a[href]').forEach(a=>{let h=a.getAttribute('href');if(!h||h.startsWith('http')||h.startsWith('tel:')||h.startsWith('mailto:')||h.startsWith('#'))return;if(h==='index.html')a.setAttribute('href','./');})}

async function fetchTeachers(){
  const url=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${SHEET_NAME}&t=${Date.now()}`;
  try{
    const res=await fetch(url),text=await res.text(),json=JSON.parse(text.substring(47).slice(0,-2));
    return json.table.rows.map(row=>{
      const c=row.c||[],newSchema=c.length>=16;
      const t=newSchema?{
        id:c[0]?.v||'',name:c[1]?.v||'',category:c[2]?.v||'',subcat:c[3]?.v||'',region:c[4]?.v||'',settlement:c[5]?.v||'',price:c[6]?.v||'',priceType:c[7]?.v||'საათში',phone:c[8]?.v||'',instagram:c[9]?.v||'',facebook:c[10]?.v||'',desc:c[11]?.v||'',online:c[12]?.v||'',photo:c[13]?.v||'',date:c[14]?.v||'',approved:String(c[15]?.v||'').toLowerCase()
      }:{
        id:c[0]?.v||'',name:c[1]?.v||'',category:c[2]?.v||'',subcat:c[3]?.v||'',region:c[4]?.v||'',settlement:'',price:c[5]?.v||'',priceType:'საათში',phone:c[6]?.v||'',instagram:c[7]?.v||'',facebook:c[8]?.v||'',desc:c[9]?.v||'',online:c[10]?.v||'',photo:c[11]?.v||'',date:c[12]?.v||'',approved:String(c[13]?.v||'').toLowerCase()
      };
      t.id=String(t.id).trim();t.settlement=String(t.settlement||'').trim();return t;
    }).filter(t=>t.name&&t.approved==='კი');
  }catch(e){console.error(e);return[]}
}

function renderCard(t){
  const ci=colorIndex(t.name),ol=String(t.online||'').toLowerCase(),isOnline=['კი','ონლაინ','ორივე'].includes(ol),isOffline=['პირადად','ორივე'].includes(ol),format=isOnline&&isOffline?'ორივე':isOnline?'ონლაინ':'პირადად';
  const img=t.photo?`<img src="${esc(t.photo)}" alt="${esc(t.name)}" loading="lazy">`:`<div class="tc-avatar ${AV_COLORS[ci]}">${esc(getInitials(t.name))}</div>`;
  return `<div class="teacher-card scroll-reveal" onclick="openProfile('${esc(t.id)}')"><div class="tc-img ${BG_COLORS[ci]}">${img}${isOnline?'<div class="tc-online-badge">ონლაინ</div>':''}</div><div class="tc-body"><div class="tc-name">${esc(t.name)}</div><div class="tc-sub">${esc(t.subcat||t.category)}</div><div class="tc-meta-row"><span class="tc-place">📍 ${esc(place(t))}</span><span class="tc-format">${esc(format)}</span></div><div class="tc-footer"><span class="tc-price">${esc(fmtPrice(t.price,t.priceType))}</span><span class="tc-open">ნახვა</span></div></div></div>`;
}
function initScrollReveal(){if(!('IntersectionObserver'in window)){document.querySelectorAll('.scroll-reveal').forEach(e=>e.classList.add('revealed'));return}const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.scroll-reveal').forEach(e=>obs.observe(e))}
function filterTeachers(arr,cat,reg,settl,fmt,minP,maxP,q){const qq=String(q||'').toLowerCase();return arr.filter(t=>{const cc=stripEmoji(cat),ol=String(t.online||'').toLowerCase(),price=parseFloat(t.price)||0;return(!cat||String(t.category).includes(cc)||String(t.subcat).includes(cc))&&(!reg||String(t.region).toLowerCase().includes(String(reg).toLowerCase()))&&(!settl||String(t.settlement).toLowerCase().includes(String(settl).toLowerCase()))&&(!fmt||(fmt==='ონლაინ'?['კი','ონლაინ','ორივე'].includes(ol):fmt==='პირადად'?!['კი','ონლაინ'].includes(ol):fmt==='ორივე'?ol==='ორივე':true))&&(price===0||(price>=minP&&price<=maxP))&&(!qq||[t.name,t.category,t.subcat,t.region,t.settlement].some(v=>String(v||'').toLowerCase().includes(qq)))})}
function ensureSettlementPill(){if(document.getElementById('pillSettlement'))return;const w=document.querySelector('.filter-pills'),r=document.getElementById('pillReg');if(!w)return;const b=document.createElement('button');b.className='filter-pill';b.id='pillSettlement';b.type='button';b.innerHTML='<span id="pillSettlementLabel">ქალაქი/სოფელი</span><span class="filter-pill-arrow">▾</span>';b.onclick=()=>openFilter('settlement');r?r.after(b):w.appendChild(b)}
function settlementOptions(){const base=Object.values(REGION_SETTLEMENTS).flat().filter(x=>x&&x!=='სხვა'),sheet=allTeachers.map(t=>t.settlement).filter(Boolean);return['',...Array.from(new Set([...base,...sheet])).sort((a,b)=>a.localeCompare(b,'ka'))]}
function openFilter(type){activeFilter=type;tempVal=type==='cat'?selectedCat:type==='reg'?selectedReg:type==='settlement'?selectedSettlement:selectedFmt;const overlay=document.getElementById('filterOverlay'),title=document.getElementById('fpTitle'),content=document.getElementById('fpContent');if(!overlay||!title||!content)return;let items=[],labels=[];if(type==='cat'){title.textContent='სფერო';items=CATEGORIES;labels=CAT_LABELS}else if(type==='reg'){title.textContent='რეგიონი';items=REGIONS;labels=REGIONS.map((r,i)=>i?'📍 '+r:'ყველა რეგიონი')}else if(type==='settlement'){title.textContent='ქალაქი / სოფელი';items=selectedReg?['',...(REGION_SETTLEMENTS[selectedReg]||[])]:settlementOptions();labels=items.map((r,i)=>i?r:'ყველა ქალაქი/სოფელი')}else{title.textContent='ფორმატი';items=FORMATS;labels=FMT_LABELS}content.innerHTML=`<div class="fp-chips">${items.map((v,i)=>`<div class="fp-chip${v===tempVal||(!v&&!tempVal)?' sel':''}" onclick="selectChip(this,'${esc(v)}')">${esc(labels[i]||v)}</div>`).join('')}</div>`;overlay.classList.add('open')}
function selectChip(el,val){document.querySelectorAll('.fp-chip').forEach(c=>c.classList.remove('sel'));el.classList.add('sel');tempVal=val}
function closeFilter(){document.getElementById('filterOverlay')?.classList.remove('open')}
function clearFilter(){tempVal='';document.querySelectorAll('.fp-chip').forEach(c=>c.classList.remove('sel'));document.querySelector('.fp-chip')?.classList.add('sel')}
function applyFilter(){if(activeFilter==='cat'){selectedCat=tempVal;const i=CATEGORIES.indexOf(tempVal);document.getElementById('pillCatLabel').textContent=tempVal?(CAT_LABELS[i]||stripEmoji(tempVal)):'ყველა სფერო';document.getElementById('pillCat').classList.toggle('active',!!tempVal)}else if(activeFilter==='reg'){selectedReg=tempVal;selectedSettlement='';document.getElementById('pillRegLabel').textContent=tempVal||'ყველა რეგიონი';document.getElementById('pillReg').classList.toggle('active',!!tempVal);document.getElementById('pillSettlementLabel').textContent='ქალაქი/სოფელი';document.getElementById('pillSettlement')?.classList.remove('active')}else if(activeFilter==='settlement'){selectedSettlement=tempVal;document.getElementById('pillSettlementLabel').textContent=tempVal||'ქალაქი/სოფელი';document.getElementById('pillSettlement')?.classList.toggle('active',!!tempVal)}else{selectedFmt=tempVal;const i=FORMATS.indexOf(tempVal);document.getElementById('pillFmtLabel').textContent=tempVal?FMT_LABELS[i]:'ნებისმიერი';document.getElementById('pillFmt').classList.toggle('active',!!tempVal)}currentPage=1;closeFilter();renderTeachers()}
function renderTeachers(){const list=document.getElementById('teachersList'),count=document.getElementById('resultsCount'),pag=document.getElementById('pagination');if(!list)return;const f=filterTeachers(allTeachers,selectedCat,selectedReg,selectedSettlement,selectedFmt,selectedMinP,selectedMaxP,searchQuery);if(count)count.textContent=`${f.length} მასწავლებელი`;if(!f.length){list.innerHTML='<div class="empty-state">ამ ფილტრით მასწავლებელი ვერ მოიძებნა</div>';if(pag)pag.innerHTML='';return}const total=Math.ceil(f.length/PAGE_SIZE);if(currentPage>total)currentPage=1;list.innerHTML=f.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE).map(renderCard).join('');setTimeout(initScrollReveal,50);if(pag){if(total<=1){pag.innerHTML='';return}let h=`<button class="page-btn" onclick="changePage(${currentPage-1})" ${currentPage===1?'disabled':''}>←</button>`;for(let i=1;i<=total;i++)h+=`<button class="page-btn${i===currentPage?' active':''}" onclick="changePage(${i})">${i}</button>`;pag.innerHTML=h+`<button class="page-btn" onclick="changePage(${currentPage+1})" ${currentPage===total?'disabled':''}>→</button>`}}
function changePage(n){currentPage=n;renderTeachers();scrollTo({top:0,behavior:'smooth'})}
function openProfile(id){location.href=`${ROUTES.teacher}?id=${encodeURIComponent(id)}`}
async function initTeachers(){ensureSettlementPill();allTeachers=await fetchTeachers();const p=new URLSearchParams(location.search);selectedCat=p.get('cat')||'';selectedReg=p.get('reg')||'';selectedSettlement=p.get('settlement')||'';selectedFmt=p.get('fmt')||'';if(selectedCat){const i=CATEGORIES.findIndex(c=>stripEmoji(c)===selectedCat||c===selectedCat);document.getElementById('pillCatLabel').textContent=i>0?CAT_LABELS[i]:selectedCat;document.getElementById('pillCat').classList.add('active')}if(selectedReg){document.getElementById('pillRegLabel').textContent=selectedReg;document.getElementById('pillReg').classList.add('active')}if(selectedSettlement){document.getElementById('pillSettlementLabel').textContent=selectedSettlement;document.getElementById('pillSettlement').classList.add('active')}if(selectedFmt){const i=FORMATS.indexOf(selectedFmt);document.getElementById('pillFmtLabel').textContent=FMT_LABELS[i]||selectedFmt;document.getElementById('pillFmt').classList.add('active')}document.getElementById('teacherSearch')?.addEventListener('input',e=>{searchQuery=e.target.value.toLowerCase().trim();currentPage=1;renderTeachers()});renderTeachers()}

const INDEX_CATS=['ყველა კატეგორია',...Object.keys(CATEGORY_DATA).map(c=>`${ICONS[c]} ${c}`)];
const INDEX_REGS=['ყველა რეგიონი',...REGIONS.slice(1).map(r=>'📍 '+r)];
function buildDropdown(ddId,items,selId,key){const dd=document.getElementById(ddId);if(!dd)return;dd.innerHTML=items.map((it,i)=>`<div class="dd-opt${i===0?' active':''}" data-val="${i?esc(stripEmoji(it)):''}" onclick="pickOption('${selId}','${ddId}','${key}',this,event)">${esc(it)}</div>`).join('')}
function pickOption(selId,ddId,key,el,e){e?.stopPropagation();document.getElementById(selId).textContent=el.textContent;document.querySelectorAll('#'+ddId+' .dd-opt').forEach(o=>o.classList.remove('active'));el.classList.add('active');document.getElementById(ddId).classList.remove('open');if(key==='cat')selectedCat=el.dataset.val;if(key==='reg')selectedReg=el.dataset.val;if(key==='fmt')selectedFmt=el.dataset.val}
function doSearch(){const p=new URLSearchParams();if(selectedCat)p.set('cat',selectedCat);if(selectedReg)p.set('reg',selectedReg);if(selectedFmt)p.set('fmt',selectedFmt);location.href=ROUTES.teachers+(p.toString()?'?'+p.toString():'')}
function goSearch(cat){location.href=ROUTES.teachers+'?cat='+encodeURIComponent(cat)}
function animateCounter(el,target,suffix=''){let s=0,inc=Math.max(1,target/75);const t=setInterval(()=>{s+=inc;if(s>=target){s=target;clearInterval(t)}el.textContent=Math.floor(s)+suffix},16)}
async function initIndex(){buildDropdown('ddCat',INDEX_CATS,'selCat','cat');buildDropdown('ddReg',INDEX_REGS,'selReg','reg');allTeachers=await fetchTeachers();const sc=document.getElementById('statCount');if(sc)animateCounter(sc,allTeachers.length,'+');const grid=document.getElementById('featuredTeachers');if(grid){const f=allTeachers.slice(-5).reverse();grid.innerHTML=f.length?f.map(renderCard).join(''):'<div class="empty-state">ჯერ მასწავლებლები არ არის დამატებული</div>';setTimeout(initScrollReveal,100)}}

async function initProfile(){const raw=new URLSearchParams(location.search).get('id'),teachers=await fetchTeachers();let d=teachers.find(t=>String(t.id)===String(raw));if(!d&&/^\d+$/.test(raw||''))d=teachers[parseInt(raw,10)];if(!d){location.href=ROUTES.teachers;return}document.title=d.name+' — Moemzade';const wrap=document.getElementById('profPhotoWrap'),img=document.getElementById('profPhoto'),ini=document.getElementById('profInitials'),bgs=['#1D9E75','#BA7517','#993556','#185FA5','#534AB7','#3B6D11'];if(wrap)wrap.style.background=bgs[colorIndex(d.name)];if(d.photo&&img&&ini){img.src=d.photo;img.style.display='block';ini.style.display='none'}else if(ini)ini.textContent=getInitials(d.name);document.getElementById('profName').textContent=d.name;document.getElementById('profSubtitle').textContent=(d.subcat||d.category)+(d.settlement?' · '+d.settlement:'');const badges=document.getElementById('profBadges'),ol=String(d.online||'').toLowerCase();if(badges){badges.innerHTML='';if(['კი','ონლაინ','ორივე'].includes(ol))badges.innerHTML+='<span class="prof-badge online">🌐 ონლაინ</span>';if(['პირადად','ორივე'].includes(ol))badges.innerHTML+='<span class="prof-badge">🏠 პირადად</span>'}const sv=(id,v,cls)=>{const el=document.getElementById(id);if(el){el.textContent=v;if(cls)el.className='pir-val '+cls}};sv('profCat',(d.subcat?d.subcat+' / ':'')+d.category);sv('profRegion',d.region||'—');ensureProfileSettlement(d.settlement||'—');sv('profPrice',fmtPrice(d.price,d.priceType)==='შეთ.'?'შეთანხმებით':fmtPrice(d.price,d.priceType),'green');sv('profPhone',d.phone||'—');if(d.instagram){document.getElementById('instRow').style.display='flex';sv('profInsta','@'+d.instagram.replace('@',''),'link')}if(d.facebook){document.getElementById('fbRow').style.display='flex';sv('profFb',d.facebook,'link')}const desc=document.getElementById('profDesc');if(desc)desc.textContent=d.desc||'—';const btns=document.getElementById('contactBtns');if(!btns)return;btns.innerHTML='';if(d.phone){const clean=String(d.phone).replace(/\s+/g,'');btns.innerHTML+=`<a href="tel:${esc(clean)}" class="contact-btn-main">📞 დარეკვა — ${esc(d.phone)}</a><a href="https://wa.me/995${esc(clean.replace(/^\+?995/,'').replace(/^0/,''))}" target="_blank" rel="noopener" class="contact-btn-main whatsapp">💬 WhatsApp-ზე მიწერა</a>`}const row=document.createElement('div');row.className='contact-btns-row';if(d.instagram)row.innerHTML+=`<a href="https://instagram.com/${esc(d.instagram.replace('@',''))}" target="_blank" rel="noopener" class="contact-btn-sec">📸 Instagram</a>`;if(d.facebook){const u=d.facebook.startsWith('http')?d.facebook:'https://facebook.com/'+d.facebook;row.innerHTML+=`<a href="${esc(u)}" target="_blank" rel="noopener" class="contact-btn-sec">📘 Facebook</a>`}if(row.children.length)btns.appendChild(row)}
function ensureProfileSettlement(v){if(document.getElementById('profSettlement')){document.getElementById('profSettlement').textContent=v;return}const reg=document.getElementById('profRegion')?.closest('.prof-info-row');if(!reg)return;const row=document.createElement('div');row.className='prof-info-row';row.innerHTML=`<span class="pir-label">ქალაქი / სოფელი</span><span class="pir-val" id="profSettlement">${esc(v)}</span>`;reg.after(row)}

function initRegisterEnhancements(){const region=document.getElementById('region'),price=document.getElementById('price'),cat=document.getElementById('category');if(!region||!price||!cat)return;cat.innerHTML='<option value="">აირჩიე სფერო</option>'+Object.keys(CATEGORY_DATA).map(c=>`<option>${esc(c)}</option>`).join('');window.updateSubcat=updateSubcatEnhanced;window.checkCustomSubcat=checkCustomSubcatEnhanced;updateSubcatEnhanced();if(!document.getElementById('settlement')){const w=document.createElement('div');w.className='fg';w.innerHTML=`<label>ქალაქი / სოფელი <span>*</span></label><select id="settlement"><option value="">ჯერ აირჩიე რეგიონი</option></select><div id="customSettlementWrap" style="display:none;margin-top:8px"><input type="text" id="customSettlement" placeholder="ჩაწერე ქალაქი ან სოფელი..."></div><div class="err-msg" id="err-settlement">აირჩიე ან ჩაწერე ქალაქი/სოფელი</div>`;region.closest('.fg-row')?.after(w)}if(!document.getElementById('priceType')){const w=document.createElement('div');w.className='fg';w.innerHTML=`<label>ფასის ტიპი <span>*</span></label><select id="priceType">${PRICE_TYPES.map(v=>`<option>${esc(v)}</option>`).join('')}</select>`;price.closest('.fg')?.after(w)}region.addEventListener('change',updateSettlementOptions);document.getElementById('settlement')?.addEventListener('change',checkCustomSettlement);updateSettlementOptions();window.submitForm=submitRegisterEnhanced}
function updateSubcatEnhanced(){const cat=document.getElementById('category')?.value||'',sub=document.getElementById('subcat');if(!sub)return;const items=CATEGORY_DATA[cat]||[];sub.innerHTML=items.length?'<option value="">აირჩიე ქვეკატეგორია</option>'+items.map(v=>`<option>${esc(v)}</option>`).join(''):'<option value="">ჯერ აირჩიე კატეგორია</option>';checkCustomSubcatEnhanced()}
function checkCustomSubcatEnhanced(){const sub=document.getElementById('subcat'),wrap=document.getElementById('customSubcatWrap');if(wrap)wrap.style.display=sub?.value==='სხვა'?'block':'none'}
function updateSettlementOptions(){const reg=document.getElementById('region')?.value||'',sel=document.getElementById('settlement');if(!sel)return;const items=REGION_SETTLEMENTS[reg]||[];sel.innerHTML=items.length?'<option value="">აირჩიე ქალაქი/სოფელი</option>'+items.map(v=>`<option>${esc(v)}</option>`).join(''):'<option value="">ჯერ აირჩიე რეგიონი</option><option>სხვა</option>';checkCustomSettlement()}
function checkCustomSettlement(){const v=document.getElementById('settlement')?.value||'',w=document.getElementById('customSettlementWrap');if(w)w.style.display=v==='სხვა'?'block':'none'}
function selectRadio(el,name){document.querySelectorAll(`input[name="${name}"]`).forEach(i=>i.closest('.radio-item')?.classList.remove('selected'));const i=el.querySelector('input');if(i)i.checked=true;el.classList.add('selected')}
function val(id){return document.getElementById(id)?.value?.trim()||''}function checked(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||''}function setErr(id,show){const e=document.getElementById(id);if(e)e.style.display=show?'block':'none'}function req(id,err){const ok=!!val(id);document.getElementById(id)?.classList.toggle('error',!ok);setErr(err,!ok);return ok}
async function submitRegisterEnhanced(){const subBtn=document.getElementById('submitBtn'),subcat=val('subcat')==='სხვა'?val('customSubcat'):val('subcat'),settle=val('settlement')==='სხვა'?val('customSettlement'):val('settlement');let ok=true;ok=req('name','err-name')&&ok;ok=req('region','err-region')&&ok;ok=!!settle&&ok;setErr('err-settlement',!settle);document.getElementById('settlement')?.classList.toggle('error',!settle);ok=req('price','err-price')&&ok;ok=req('category','err-category')&&ok;const descOk=val('desc').length>=30;document.getElementById('desc')?.classList.toggle('error',!descOk);setErr('err-desc',!descOk);ok=descOk&&ok;const fmtOk=!!checked('format');setErr('err-format',!fmtOk);ok=fmtOk&&ok;ok=req('phone','err-phone')&&ok;if(!ok)return;const data={name:val('name'),category:val('category'),subcat,region:val('region'),settlement:settle,price:val('price'),priceType:val('priceType')||'საათში',phone:val('phone'),instagram:val('instagram'),facebook:val('facebook'),desc:val('desc'),format:checked('format'),photo:val('photoUrl'),date:new Date().toLocaleString('ka-GE')};try{if(subBtn){subBtn.disabled=true;subBtn.textContent='იგზავნება...'}await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)});document.getElementById('formCard').style.display='none';document.getElementById('successCard')?.classList.add('show');scrollTo({top:0,behavior:'smooth'})}catch(e){alert('გაგზავნა ვერ მოხერხდა. სცადე თავიდან.')}finally{if(subBtn){subBtn.disabled=false;subBtn.textContent='პროფილის გამოქვეყნება ✓'}}}

document.addEventListener('DOMContentLoaded',()=>{addRuntimeCss();cleanLinks();const page=document.body.dataset.page;if(page==='index')initIndex();if(page==='teachers')initTeachers();if(page==='profile')initProfile();if(document.body.classList.contains('reg-page'))initRegisterEnhancements();setTimeout(()=>{cleanLinks();initScrollReveal()},200)});
